# Generated by Django 2.0.4 on 2018-07-31 12:49

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, max_length=64, verbose_name='Имя')),
                ('lastName', models.CharField(blank=True, max_length=64, verbose_name='Фамилия')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')),
                ('lat', models.DecimalField(blank=True, decimal_places=10, max_digits=19, verbose_name='Ширина')),
                ('lon', models.DecimalField(blank=True, decimal_places=10, max_digits=19, verbose_name='Долгота')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, verbose_name='Телефон')),
            ],
        ),
    ]
