# Generated by Django 2.0.4 on 2018-08-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Ширина'),
        ),
        migrations.AlterField(
            model_name='human',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Долгота'),
        ),
    ]
