# Generated by Django 2.0.4 on 2018-08-01 10:00

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_auto_20180801_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='human',
            name='firstName',
            field=models.CharField(max_length=64, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='human',
            name='lastName',
            field=models.CharField(max_length=64, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='human',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=9, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='human',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, verbose_name='Телефон'),
        ),
    ]
