# Generated by Django 2.0.4 on 2018-08-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20180801_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=9, null=True, verbose_name='Ширина'),
        ),
    ]
