# Generated by Django 2.0.4 on 2018-08-01 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_auto_20180801_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='human',
            name='lon',
            field=models.DecimalField(blank=True, decimal_places=7, default=0, max_digits=10, null=True, verbose_name='Долгота'),
        ),
    ]
